apiVersion: v1
kind: Service
metadata:
  name: places-api
  labels:
    app: places-api
    service: places-api
spec:
  ports:
    - port: 5030
      name: grpc
  selector:
    app: places-api
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: places-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: places-api
  labels:
    app: places-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: places-api
  template:
    metadata:
      labels:
        app: places-api
    spec:
      nodeSelector:
        service: general
      serviceAccountName: places-api
      containers:
        - name: places-api
          image: microapis/places-api:0.0.7
          ports:
            - containerPort: 5030
          env:
            - name: API_KEY
              value: <API_KEY>
            - name: PORT
              value: "5030"
            - name: NATS_HOST
              value: nats
            - name: NATS_PORT
              value: "4222"
          resources:
            requests:
              cpu: 100m
              memory: 256Mi
            limits:
              cpu: 200m
              memory: 512Mi
