// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/places.proto

package proto

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type PlaceError struct {
	Code                 int32    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Message              string   `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceError) Reset()         { *m = PlaceError{} }
func (m *PlaceError) String() string { return proto.CompactTextString(m) }
func (*PlaceError) ProtoMessage()    {}
func (*PlaceError) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b635ff9d2e2d652, []int{0}
}

func (m *PlaceError) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceError.Unmarshal(m, b)
}
func (m *PlaceError) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceError.Marshal(b, m, deterministic)
}
func (m *PlaceError) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceError.Merge(m, src)
}
func (m *PlaceError) XXX_Size() int {
	return xxx_messageInfo_PlaceError.Size(m)
}
func (m *PlaceError) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceError.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceError proto.InternalMessageInfo

func (m *PlaceError) GetCode() int32 {
	if m != nil {
		return m.Code
	}
	return 0
}

func (m *PlaceError) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

type Coord struct {
	Latitude             float64  `protobuf:"fixed64,1,opt,name=latitude,proto3" json:"latitude,omitempty"`
	Longitude            float64  `protobuf:"fixed64,2,opt,name=longitude,proto3" json:"longitude,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Coord) Reset()         { *m = Coord{} }
func (m *Coord) String() string { return proto.CompactTextString(m) }
func (*Coord) ProtoMessage()    {}
func (*Coord) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b635ff9d2e2d652, []int{1}
}

func (m *Coord) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Coord.Unmarshal(m, b)
}
func (m *Coord) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Coord.Marshal(b, m, deterministic)
}
func (m *Coord) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Coord.Merge(m, src)
}
func (m *Coord) XXX_Size() int {
	return xxx_messageInfo_Coord.Size(m)
}
func (m *Coord) XXX_DiscardUnknown() {
	xxx_messageInfo_Coord.DiscardUnknown(m)
}

var xxx_messageInfo_Coord proto.InternalMessageInfo

func (m *Coord) GetLatitude() float64 {
	if m != nil {
		return m.Latitude
	}
	return 0
}

func (m *Coord) GetLongitude() float64 {
	if m != nil {
		return m.Longitude
	}
	return 0
}

type Place struct {
	Id                   string   `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name                 string   `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Rating               string   `protobuf:"bytes,3,opt,name=rating,proto3" json:"rating,omitempty"`
	Address              string   `protobuf:"bytes,4,opt,name=address,proto3" json:"address,omitempty"`
	Open                 bool     `protobuf:"varint,5,opt,name=open,proto3" json:"open,omitempty"`
	PhotoReference       string   `protobuf:"bytes,6,opt,name=photo_reference,json=photoReference,proto3" json:"photo_reference,omitempty"`
	Coord                *Coord   `protobuf:"bytes,7,opt,name=coord,proto3" json:"coord,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Place) Reset()         { *m = Place{} }
func (m *Place) String() string { return proto.CompactTextString(m) }
func (*Place) ProtoMessage()    {}
func (*Place) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b635ff9d2e2d652, []int{2}
}

func (m *Place) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Place.Unmarshal(m, b)
}
func (m *Place) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Place.Marshal(b, m, deterministic)
}
func (m *Place) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Place.Merge(m, src)
}
func (m *Place) XXX_Size() int {
	return xxx_messageInfo_Place.Size(m)
}
func (m *Place) XXX_DiscardUnknown() {
	xxx_messageInfo_Place.DiscardUnknown(m)
}

var xxx_messageInfo_Place proto.InternalMessageInfo

func (m *Place) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Place) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Place) GetRating() string {
	if m != nil {
		return m.Rating
	}
	return ""
}

func (m *Place) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *Place) GetOpen() bool {
	if m != nil {
		return m.Open
	}
	return false
}

func (m *Place) GetPhotoReference() string {
	if m != nil {
		return m.PhotoReference
	}
	return ""
}

func (m *Place) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

type PlaceListByCoordRequest struct {
	Coord                *Coord   `protobuf:"bytes,1,opt,name=coord,proto3" json:"coord,omitempty"`
	UserId               string   `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlaceListByCoordRequest) Reset()         { *m = PlaceListByCoordRequest{} }
func (m *PlaceListByCoordRequest) String() string { return proto.CompactTextString(m) }
func (*PlaceListByCoordRequest) ProtoMessage()    {}
func (*PlaceListByCoordRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b635ff9d2e2d652, []int{3}
}

func (m *PlaceListByCoordRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceListByCoordRequest.Unmarshal(m, b)
}
func (m *PlaceListByCoordRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceListByCoordRequest.Marshal(b, m, deterministic)
}
func (m *PlaceListByCoordRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceListByCoordRequest.Merge(m, src)
}
func (m *PlaceListByCoordRequest) XXX_Size() int {
	return xxx_messageInfo_PlaceListByCoordRequest.Size(m)
}
func (m *PlaceListByCoordRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceListByCoordRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceListByCoordRequest proto.InternalMessageInfo

func (m *PlaceListByCoordRequest) GetCoord() *Coord {
	if m != nil {
		return m.Coord
	}
	return nil
}

func (m *PlaceListByCoordRequest) GetUserId() string {
	if m != nil {
		return m.UserId
	}
	return ""
}

type PlaceListByCoordResponse struct {
	Data                 []*Place    `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	Error                *PlaceError `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	XXX_NoUnkeyedLiteral struct{}    `json:"-"`
	XXX_unrecognized     []byte      `json:"-"`
	XXX_sizecache        int32       `json:"-"`
}

func (m *PlaceListByCoordResponse) Reset()         { *m = PlaceListByCoordResponse{} }
func (m *PlaceListByCoordResponse) String() string { return proto.CompactTextString(m) }
func (*PlaceListByCoordResponse) ProtoMessage()    {}
func (*PlaceListByCoordResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_3b635ff9d2e2d652, []int{4}
}

func (m *PlaceListByCoordResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlaceListByCoordResponse.Unmarshal(m, b)
}
func (m *PlaceListByCoordResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlaceListByCoordResponse.Marshal(b, m, deterministic)
}
func (m *PlaceListByCoordResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlaceListByCoordResponse.Merge(m, src)
}
func (m *PlaceListByCoordResponse) XXX_Size() int {
	return xxx_messageInfo_PlaceListByCoordResponse.Size(m)
}
func (m *PlaceListByCoordResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PlaceListByCoordResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PlaceListByCoordResponse proto.InternalMessageInfo

func (m *PlaceListByCoordResponse) GetData() []*Place {
	if m != nil {
		return m.Data
	}
	return nil
}

func (m *PlaceListByCoordResponse) GetError() *PlaceError {
	if m != nil {
		return m.Error
	}
	return nil
}

func init() {
	proto.RegisterType((*PlaceError)(nil), "proto.PlaceError")
	proto.RegisterType((*Coord)(nil), "proto.Coord")
	proto.RegisterType((*Place)(nil), "proto.Place")
	proto.RegisterType((*PlaceListByCoordRequest)(nil), "proto.PlaceListByCoordRequest")
	proto.RegisterType((*PlaceListByCoordResponse)(nil), "proto.PlaceListByCoordResponse")
}

func init() { proto.RegisterFile("proto/places.proto", fileDescriptor_3b635ff9d2e2d652) }

var fileDescriptor_3b635ff9d2e2d652 = []byte{
	// 359 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x74, 0x51, 0x4d, 0x6b, 0xdb, 0x40,
	0x10, 0xed, 0xca, 0x96, 0x3f, 0xc6, 0xc6, 0xa5, 0x73, 0xa8, 0x17, 0x53, 0x5a, 0xa1, 0x8b, 0x75,
	0x72, 0xc1, 0xbd, 0xf5, 0xd6, 0x96, 0x1e, 0x0a, 0x3d, 0x98, 0x0d, 0xe4, 0xea, 0x6c, 0xb4, 0x13,
	0x47, 0x60, 0x6b, 0x95, 0xdd, 0x75, 0x20, 0x7f, 0x2e, 0xbf, 0x2d, 0x68, 0x64, 0xc5, 0x02, 0xe3,
	0x93, 0xe6, 0xbd, 0x37, 0x6f, 0xe6, 0x8d, 0x16, 0xb0, 0x72, 0x36, 0xd8, 0xef, 0xd5, 0x5e, 0xe7,
	0xe4, 0x57, 0x0c, 0x30, 0xe6, 0x4f, 0xfa, 0x13, 0x60, 0x53, 0xd3, 0x7f, 0x9d, 0xb3, 0x0e, 0x11,
	0xfa, 0xb9, 0x35, 0x24, 0x45, 0x22, 0xb2, 0x58, 0x71, 0x8d, 0x12, 0x86, 0x07, 0xf2, 0x5e, 0xef,
	0x48, 0x46, 0x89, 0xc8, 0xc6, 0xaa, 0x85, 0xe9, 0x2f, 0x88, 0xff, 0x58, 0xeb, 0x0c, 0x2e, 0x60,
	0xb4, 0xd7, 0xa1, 0x08, 0xc7, 0x93, 0x55, 0xa8, 0x77, 0x8c, 0x5f, 0x60, 0xbc, 0xb7, 0xe5, 0xae,
	0x11, 0x23, 0x16, 0xcf, 0x44, 0xfa, 0x2a, 0x20, 0xe6, 0xfd, 0x38, 0x83, 0xa8, 0x30, 0xec, 0x1e,
	0xab, 0xa8, 0x30, 0x75, 0x94, 0x52, 0x1f, 0xda, 0x9d, 0x5c, 0xe3, 0x67, 0x18, 0x38, 0x1d, 0x8a,
	0x72, 0x27, 0x7b, 0xcc, 0x9e, 0x50, 0x1d, 0x51, 0x1b, 0xe3, 0xc8, 0x7b, 0xd9, 0x6f, 0x22, 0x9e,
	0x60, 0x3d, 0xc5, 0x56, 0x54, 0xca, 0x38, 0x11, 0xd9, 0x48, 0x71, 0x8d, 0x4b, 0xf8, 0x58, 0x3d,
	0xda, 0x60, 0xb7, 0x8e, 0x1e, 0xc8, 0x51, 0x99, 0x93, 0x1c, 0xb0, 0x6b, 0xc6, 0xb4, 0x6a, 0x59,
	0x4c, 0x21, 0xce, 0xeb, 0xfb, 0xe4, 0x30, 0x11, 0xd9, 0x64, 0x3d, 0x6d, 0xfe, 0xdc, 0x8a, 0x6f,
	0x56, 0x8d, 0x94, 0xde, 0xc2, 0x9c, 0xf3, 0xff, 0x2f, 0x7c, 0xf8, 0xfd, 0xd2, 0x48, 0xf4, 0x74,
	0x24, 0x1f, 0xce, 0x76, 0x71, 0xd5, 0x8e, 0x73, 0x18, 0x1e, 0x3d, 0xb9, 0x6d, 0x61, 0xda, 0x93,
	0x6a, 0xf8, 0xcf, 0xa4, 0x04, 0xf2, 0x72, 0xae, 0xaf, 0x6c, 0xe9, 0x09, 0x13, 0xe8, 0x1b, 0x1d,
	0xb4, 0x14, 0x49, 0xaf, 0x33, 0x97, 0xdb, 0x15, 0x2b, 0xb8, 0x84, 0x98, 0xea, 0x07, 0xe5, 0xbf,
	0x37, 0x59, 0x7f, 0xea, 0xb6, 0xf0, 0x4b, 0xab, 0x46, 0x5f, 0xdf, 0xc1, 0x94, 0xc9, 0x1b, 0x72,
	0xcf, 0x45, 0x4e, 0xb8, 0x81, 0x49, 0x67, 0x23, 0x7e, 0xed, 0x1a, 0x2f, 0x4f, 0x5c, 0x7c, 0xbb,
	0xaa, 0x37, 0x51, 0xd3, 0x0f, 0xf7, 0x03, 0xee, 0xf8, 0xf1, 0x16, 0x00, 0x00, 0xff, 0xff, 0x83,
	0x67, 0x6d, 0x6a, 0x84, 0x02, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// PlaceServiceClient is the client API for PlaceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type PlaceServiceClient interface {
	ListByCoord(ctx context.Context, in *PlaceListByCoordRequest, opts ...grpc.CallOption) (*PlaceListByCoordResponse, error)
}

type placeServiceClient struct {
	cc *grpc.ClientConn
}

func NewPlaceServiceClient(cc *grpc.ClientConn) PlaceServiceClient {
	return &placeServiceClient{cc}
}

func (c *placeServiceClient) ListByCoord(ctx context.Context, in *PlaceListByCoordRequest, opts ...grpc.CallOption) (*PlaceListByCoordResponse, error) {
	out := new(PlaceListByCoordResponse)
	err := c.cc.Invoke(ctx, "/proto.PlaceService/ListByCoord", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PlaceServiceServer is the server API for PlaceService service.
type PlaceServiceServer interface {
	ListByCoord(context.Context, *PlaceListByCoordRequest) (*PlaceListByCoordResponse, error)
}

func RegisterPlaceServiceServer(s *grpc.Server, srv PlaceServiceServer) {
	s.RegisterService(&_PlaceService_serviceDesc, srv)
}

func _PlaceService_ListByCoord_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(PlaceListByCoordRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PlaceServiceServer).ListByCoord(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/proto.PlaceService/ListByCoord",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PlaceServiceServer).ListByCoord(ctx, req.(*PlaceListByCoordRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _PlaceService_serviceDesc = grpc.ServiceDesc{
	ServiceName: "proto.PlaceService",
	HandlerType: (*PlaceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListByCoord",
			Handler:    _PlaceService_ListByCoord_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/places.proto",
}
